export const listeClauses = [
  {
    idContrat: 1,
    ori: 'PAR',
    des: 'TLS',
    cdr: 'C',
    farebasis: 'FULL-FLEX',
    cie: 'AF',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 23,
  },
  {
    idContrat: 1,
    ori: 'PAR',
    des: 'TLS',
    cdr: 'D',
    farebasis: 'SEMI-FLEX',
    cie: 'AF',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 15,
  },
  {
    idContrat: 1,
    ori: 'PAR',
    des: 'TLS',
    cdr: 'Y',
    //farebasis: '',
    upgradable: 1,
    cie: 'AF',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 4,
  },
  {
    idContrat: 1,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'C',
    farebasis: 'FULL-FLEX',
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 35,
  },
  {
    idContrat: 1,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'D',
    farebasis: 'SEMI-FLEX',
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 22,
  },
  {
    idContrat: 1,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'KL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 5,
},
  {
    idContrat: 1,
    ori: 'TLS',
    des: 'SIN',
    cdr: 'Y',
    farebasis: '',
    upgradable: 1,
    cie: 'DL',
    ddv: '01/01/2020',
    dfv: '31/12/2020',
    remise: 3,
  },
  
];